server:
  port: 5060

spring:
  application:
    name: "prophius-assessment"

  profiles:
    active: postgres

  devtools:
    restart:
      enabled: true

  security:
    user:
      roles: admin


app:
  jwt-config:
    secret-key: ${SECRET_KEY:TRYBDHBBU9402hHKNJBBBBJBSJBJIHIHJBHNJNJJFDVSJNJGFNJJVJDNJN}

---

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,loggers,caches, mappings


springdoc:
  show-actuator: true
  swagger-ui:
    enabled: true
    operationsSorter: method
    path: /swagger-ui.html
  api-docs:
    path: /api=docs


---

aws:
  storage:
    bucket-name: bucketname
    access-key: accesskey
    secret-key: secretkey
    region: AP_NORTHEAST_1


---

azure:
  storage:
    account-name: abs-account-name
    account-key: abs-account-key
    container-name: abs-container-name
    blob-endpoint: "https://${azure.storage.account-name}.blob.core.windows.net/${azure.storage.container-name}"


---

google:
  cloud:
    storage:
      application-credentials: "C:/path/to/file"
      project-id: XXX-XXX
      bucket-name: bucketname



