server:
  port: 5060

spring:
  application:
    name: "prophius-assessment"

  profiles:
    active: postgres

  devtools:
    restart:
      enabled: true

  security:
    user:
      roles: admin


app:
  jwt-config:
    secret-key: ${SECRET_KEY:TRYBDHBBU9402hHKNJBBBBJBSJBJIHIHJBHNJNJJFDVSJNJGFNJJVJDNJN}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,loggers,caches, mappings


springdoc:
  show-actuator: true
  swagger-ui:
    enabled: true
    operationsSorter: method
    path: /swagger-ui.html
  api-docs:
    path: /api=docs



